### ISSUE TITLE
Tracking issue for v1.0

### ISSUE THREAD

**Issue by MikailBag** [MikailBag/jjs#5]
Things that must be done:
- [ ] implement access control
- [ ] API for contests (perhaps stub), submissions

**Comment by pavel-the-best** [comment]
Any updates on this?

**Comment by MikailBag** [comment]
Well, new list looks like:
 - [ ] Many important simple lacking features (like user password modification).
 - [ ] Finish major refactorings.
